services:
  pion-api:
    build:
      context: .
      dockerfile: ./pion-api/Dockerfile
    ports:
      - "8080:8080"
      - "8443:443"
    container_name: pion-api
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Admin@123
      - ASPNETCORE_URLS=http://+:8080;https://+:443
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys
